Adding utilitiies module
ProjectDrawdown/solutions pull request #358
Opened 2021-07-25 17:45 UTC by ssmssam

#347  #WIP 
draft PR 
Need to generalise the class to a meta class and then create the other conversion tables using this.
Just want feedback on if this EnergyConversion class would be useful as it stands first

2021-07-27 09:07 UTC, ssmssam commented
metaclass added along with unit tests for all the conversion classes and functions

2021-07-28 18:22 UTC, denised requested changes

2021-07-28 18:22 UTC, denised commented on solution/afforestation/__init__.py
> +            fc_convert_iunit_factor=conversions.mha_to_ha())
@ssmssam I was confused for a bit until I figured out how this is working.  I think it would be clearer if you explicitly put the default argument in.
````
fc_convert_iunit_factor=conversions.mha_to_ha(1)
````

It would be even more clear if the argument were changed like so:
````
fc_iunit_conversion=conversions.mha_to_ha
````
And then the First Cost code was changed to call the conversion function provided.   I'll leave it to you if you'd like to make this second improvement.

2021-07-29 06:51 UTC, denised approved these changes
Very nice.  Very clean work, thank you!

2021-07-29 06:51 UTC, ssmssam commented on solution/afforestation/__init__.py
> +            fc_convert_iunit_factor=conversions.mha_to_ha())
I went down the second route, so FirstCost and OperatingCost will call the conversion factor if it is a function otherwise they will take its existing value

2021-07-29 16:44 UTC, merged