First four ocean solutions to be added to main repository.
ProjectDrawdown/solutions pull request #415
Opened 2021-08-27 07:28 UTC by glass-wing

Seaweed Farming, Macroalgae Restoration, Macroalgae Protection and Seafloor Protection all working.
Seafloor Restoration included but not yet working properly.

2021-08-29 03:00 UTC, denised requested changes
You'll need to fix the absolute file references in the yaml files.

2021-08-29 03:00 UTC, denised commented on solution/macroalgaeprotection/macroalgaeprotection_solution_config.yaml
> +REFAdoptionFile: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/macroalgaeprotection/unit_adoption_data/custom_ref_adoption.json
You'll need to make these relative file references!

2021-08-29 03:48 UTC, glass-wing commented on solution/macroalgaeprotection/macroalgaeprotection_solution_config.yaml
> +REFAdoptionFile: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/macroalgaeprotection/unit_adoption_data/custom_ref_adoption.json
Ok, they're relative now. Thanks for pointing that out.

2021-09-03 03:33 UTC, glass-wing commented
Individual solutions are structurally complete. Most tests are passing, just the CO2 ppm equivalent tests are failing. Marked these as "skip" in pytest.

2021-09-03 18:37 UTC, merged