First look at script to extract data from expected.zip and update the…
ProjectDrawdown/solutions pull request #468
Opened 2021-09-25 00:13 UTC by johnpaulalex

… scenario jsons. Does not include the ~300 modified json's.

Note also that there's one expected.zip which needs a slight tweak for this to totally work - there's a space at the end of one of the scenario subdirs.

2021-09-25 04:55 UTC, denised commented on tools/copy_expected_to_scenario.py
> +            sr_file = zf.open(scenario_name + "/" + 'ScenarioRecord')
And in fact if the information you need is _on_ the ScenarioRecord tab, you only need to read that tab once --- this tab does not change from scenario to scenario.
For other situations, you might need to do something different.

2021-09-25 05:00 UTC, denised commented on tools/copy_expected_to_scenario.py
> +def all_solutions(solution_basedir):
There's a function for this already in factory.py.  Unless there's a reason to avoid that dependency, you might as well use it.

2021-09-25 05:03 UTC, denised commented on tools/copy_expected_to_scenario.py
> +all_jsons_modified = []
Our standard practice is to navigate from wherever the file is to where you need to look via the __path__ magic variable.  So you don't need to hardcode a path here;  in pathlib terms it is Path(__file__).parent[1]/"solution"

2021-09-25 05:05 UTC, denised commented on tools/copy_expected_to_scenario.py
> +# Run over all solutions.
Even though this is an example script, I'd prefer to see "if __name__ == '__main__'" at the top of the script part.

2021-09-25 05:10 UTC, denised commented on tools/copy_expected_to_scenario.py
> +            sxe.write_scenario(jsonfile, d)
Missing dependency sxe?  Or am I not seeing it somewhere...

2021-09-25 05:13 UTC, denised requested changes
A couple of nits to fix, but I like it.
I think for educational purposes, it would be good to demonstrate reading the ScenarioRecord once only, but also leave a function that can find the file in the zip for a (scenario, tab) combination

2021-09-25 11:13 UTC, johnpaulalex commented
Thanks Denise. All the comments SGTM except reading ScenarioRecord once.  I had considered that but I thought it's _not_ guaranteed to be the same across scenarios due to the updates we plan to support:
   * export scenarios 1, 2, 3 - each has a ScenarioRecord with all 3 scenarios.
   * later, export scenario 4.  It has a ScenarioRecord with all 4, the others don't.
My conclusion was that the only trustworthy version of scenario x's ScenarioRecord is in scenario x's directory. This also seems consistent with the general idea that scenario x's directory holds all scenario x data; the other scenario rows are just noise.

...or can we assume that every export will always update all scenarios?  I guess I thought earlier scenarios might sometimes become unexportable or you simply might want to keep them frozen.  Or you might run the export method and want to revert some of the changes it made to existing files, for some other reason...

2021-09-25 23:19 UTC, denised commented
That's a good caution to take, but in this case you can assume that ScenarioRecord is fixed.  We create expected.zip all at once, and we dump everything from the Excel into expected.zip

-- 
  Denise Draper
  ***@***.***



On Sat, Sep 25, 2021, at 4:14 AM, johnpaulalex wrote:
> 
> 
> Thanks Denise. All the comments SGTM except reading ScenarioRecord once. I had considered that but I thought it's *not* guaranteed to be the same across scenarios due to the updates we plan to support:
> 
>  * export scenarios 1, 2, 3 - each has a ScenarioRecord with all 3 scenarios.
>  * later, export scenario 4. It has a ScenarioRecord with all 4, the others don't.
> My conclusion was that the only trustworthy version of scenario x's ScenarioRecord is in scenario x's directory. This also seems consistent with the general idea that scenario x's directory holds all scenario x data; the other scenario rows are just noise.
> ...or can we assume that every export will always update all scenarios? I guess I thought earlier scenarios might sometimes become unexportable or you simply might want to keep them frozen. Or you might run the export method and want to revert some of the changes it made to existing files, for some other reason...
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/ProjectDrawdown/solutions/pull/468#issuecomment-927106011>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAKAMTTA3BFUJEI6DWTV5ZTUDWVHVANCNFSM5EW6M2OQ>.
>

2021-09-26 00:13 UTC, denised commented
Actually now that I think about it a bit more, I think you are right.   We create expected.zip all at once now, but we might do that differently later.

-- 
  Denise Draper
  ***@***.***



On Sat, Sep 25, 2021, at 4:19 PM, Denise Draper wrote:
> That's a good caution to take, but in this case you can assume that ScenarioRecord is fixed.  We create expected.zip all at once, and we dump everything from the Excel into expected.zip
> 
> -- 
>   Denise Draper
>   ***@***.***
> 
> 
> 
> On Sat, Sep 25, 2021, at 4:14 AM, johnpaulalex wrote:
>> 
>> 
>> Thanks Denise. All the comments SGTM except reading ScenarioRecord once. I had considered that but I thought it's *not* guaranteed to be the same across scenarios due to the updates we plan to support:
>> 
>>  * export scenarios 1, 2, 3 - each has a ScenarioRecord with all 3 scenarios.
>>  * later, export scenario 4. It has a ScenarioRecord with all 4, the others don't.
>> My conclusion was that the only trustworthy version of scenario x's ScenarioRecord is in scenario x's directory. This also seems consistent with the general idea that scenario x's directory holds all scenario x data; the other scenario rows are just noise.
>> ...or can we assume that every export will always update all scenarios? I guess I thought earlier scenarios might sometimes become unexportable or you simply might want to keep them frozen. Or you might run the export method and want to revert some of the changes it made to existing files, for some other reason...
>> 
>> 
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub <https://github.com/ProjectDrawdown/solutions/pull/468#issuecomment-927106011>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAKAMTTA3BFUJEI6DWTV5ZTUDWVHVANCNFSM5EW6M2OQ>.
>> 
>> 
>

2021-09-26 13:18 UTC, johnpaulalex commented on tools/copy_expected_to_scenario.py
> +def all_solutions(solution_basedir):
SG but when I tried 'from solution import factory' and then ran 'python tools/copy_expected_to_scenario.py', it complained that it couldn't find the 'solution' module.  I feel like I'm missing something basic here.  I thought there might need to be a solution/__init__.py to signal that it's a module directory, but I see you import this module in other files already...

2021-09-26 21:37 UTC, denised commented on tools/copy_expected_to_scenario.py
> +def all_solutions(solution_basedir):
It took me forever to figure this out...
When you execute a script like so:
```
python foo/bar.py
```
Python executes that script *outside* the package hierarchy, and so the code will only find the imports if you have added the solutions directory to your Python path.
When you execute a script like so:
```
python -m foo.bar
```
it operates within the python package hierarchy and relative imports work.

One way I get around this is by working in Jupyter Notebook a lot, and my notebooks always begin by adding solutions to the python path.

(And I only figured this out recently: the reason there is a file `rrs.py` in the tools directory is because I couldn't figure out how to get the relative path working and I just got frustrated and copied the file :-)

2021-09-28 21:31 UTC, johnpaulalex commented on tools/copy_expected_to_scenario.py
> +            sr_file = zf.open(scenario_name + "/" + 'ScenarioRecord')
as discussed offline, leaving logic as-is. I added a comment about a contract for ScenarioRecord: only trust the data about scenario x when reading scenario x's ScenarioRecord.

2021-09-28 21:32 UTC, johnpaulalex commented on tools/copy_expected_to_scenario.py
> +def all_solutions(solution_basedir):
wow that is really good to know, thanks! All good now.

2021-09-28 21:32 UTC, johnpaulalex commented on tools/copy_expected_to_scenario.py
> +# Run over all solutions.
done

2021-09-28 21:32 UTC, johnpaulalex commented on tools/copy_expected_to_scenario.py
> +            sxe.write_scenario(jsonfile, d)
fixed

2021-09-28 22:58 UTC, denised approved these changes

2021-09-28 23:07 UTC, merged